#!/bin/bash

# Create the lb service, then activate it and start it

echo "
[Unit]
Description=Gunicorn instance to serve Load Balancer Application
After=network.target

[Service]
User=$USER
WorkingDirectory=/home/$USER/SDN_Load_Balancer
ExecStart=/home/$USER/SDN_Load_Balancer/venv/bin/gunicorn -b 0.0.0.0:8001 --access-logfile - --chdir /home/$USER/SDN_Load_Balancer \"lb_api:create_app()\"

[Install]
WantedBy=multi-user.target

" > lb.service

sleep 2
sudo mv lb.service /etc/systemd/system/
sleep 2
sudo systemctl enable lb
sleep 2
sudo systemctl start lb
sleep 2
sudo systemctl status lb